name: first

on: [push]

jobs:
  ubuntu-latest:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: date
  windows-latest:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: "Get-Date"
  macos-latest:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: date
  macos-10:
    needs: [macos-latest, ubuntu-latest, windows-latest]
    name: Fourth job
    runs-on: macos-10.15
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: date
